version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile.dev
    ports:
      - "8800:8800"
    volumes:
      - ./api:/app
      - /app/node_modules
