# frontend/Dockerfile

# 1. Build React app
FROM node:18-alpine AS builder
ARG CONTEXT
WORKDIR /$CONTEXT

COPY $CONTEXT/package*.json ./
RUN npm install
COPY $CONTEXT/ ./
RUN npm run build

# 2. Serve with Nginx
FROM nginx:alpine
ARG CONTEXT
COPY --from=builder /$CONTEXT/build /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
