# Builder
FROM node:18-alpine AS builder
WORKDIR /app

COPY api/package*.json ./
RUN npm install
COPY api/ ./
RUN npm run build
RUN npx prisma generate

# Final
FROM node:18-alpine
WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/prisma ./prisma
COPY api/package*.json ./

CMD ["node", "dist/index.js"]
