name: CI - Build

on:
  push:
    branches: [main, test-ci]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build backend image
        run: |
          docker build -f infra/docker/backend/Dockerfile.prod --build-arg CONTEXT=api -t zentra-backend .

      - name: Build frontend image
        run: |
          docker build -f infra/docker/frontend/Dockerfile.prod --build-arg CONTEXT=frontend -t zentra-frontend .

      - name: Confirm success
        run: echo "✅ CI ran successfully and both images were built!"

      # Optional: Add test steps here later!
      # e.g., docker run --rm airbnb-backend npm test
